TV_thresh: 0.8
accLim: 1.2
bottomColor: '#00aa00'
dataDir: D:\Users\thomas\Data\CloudStation\Projects\IMUs\Jansenberger\data
gyrLim: 300.0
init_channel: 0
lower_thresh: 0.3
middleColor: '#ffaa00'
opening_view: 0
topColor: red
upper_thresh: 0.7
