accLim: 1.2
bottomColor: '#00aa00'
dataDir: D:\Users\thomas\Data\CloudStation\Projects\IMUs\Jansenberger\data
gyrLim: 300.0
initSensortype: 0
lowerThresh: 0.3
middleColor: '#ffaa00'
openingView: 0
sensor0: 8015
sensor1: 0
thresholds: 0.8
topColor: red
upperThresh: 0.7
